// <auto-generated />
namespace WindowsFormsApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddDesc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDesc));
        
        string IMigrationMetadata.Id
        {
            get { return "202004161549237_AddDesc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
